[[redirects]]
  from = "/site.webmanifest"
  to = "https://cdn.greasyfork.org.cn/site.webmanifest"
  status = 200
  force = true

[[redirects]]
  from = "/favicon-32x32.png"
  to = "https://cdn.greasyfork.org.cn/favicon-32x32.png"
  status = 200
  force = true

[[redirects]]
  from = "/favicon-16x16.png"
  to = "https://cdn.greasyfork.org.cn/favicon-16x16.png"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://cdn.greasyfork.org.cn/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "https://cdn.greasyfork.org.cn/apple-touch-icon.png"
  status = 200
  force = true

[[redirects]]
  from = "/android-chrome-512x512.png"
  to = "https://cdn.greasyfork.org.cn/android-chrome-512x512.png"
  status = 200
  force = true

[[redirects]]
  from = "/android-chrome-192x192.png"
  to = "https://cdn.greasyfork.org.cn/android-chrome-192x192.png"
  status = 200
  force = true

[[redirects]]
  from = "/efa18acc-c5b8-480d-bf3f-ee419de809e3"
  to = "https://dgkkhxhkj.dahi.edu.eu.org/zh-CN/scripts.json"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "https://cdn.greasyfork.org.cn/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://home.greasyfork.org.cn/404"
  status = 308
